name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache Poetry dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry
            ~/.cache/pip
          key: poetry-${{ runner.os }}-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            poetry-${{ runner.os }}-

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry nox-poetry

      - name: Install Nox
        run: pip install nox

      - name: Install project dependencies
        run: poetry install --no-interaction --no-root

      - name: Run tests with Nox (reuse Poetry env to avoid "no space left on device" errors)
        run: poetry run nox -rs tests --no-venv
